spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL55Dialect
    open-in-view: true
  thymeleaf:
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: blog
      url: jdbc:log4jdbc:mysql:///blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      driver-class-name: net.sf.log4jdbc.DriverSpy
      username: root
      password: root
      filters: stat
      maxActive: 30
      initialSize: 10
      maxWait: 30000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 18000000
      minEvictableIdleTimeMillis: 18000000
      maxEvictableIdleTimeMillis: 28800000
      testWhileIdle: true
      validationQuery: select 1
      maxOpenPreparedStatements: 50
logging:
  level:
    root: info
    io.github.ramerf.blog: debug
    jdbc.resultset: off
    jdbc.audit: off
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator: error
server:
  port: 8080
  servlet:
    context-path: /
    session:
      tracking-modes: cookie,url
      cookie:
        http-only: true
io:
  github:
    ramerf:
      blog:
        resource-path: C:/Users/ramer/Desktop/
        netdisk: C:/Users/ramer/Desktop/
wind:
  entity-package: io.github.ramerf.blog.entity.pojo